export const WORD_CATEGORIES: Record<string, string[]> = {
  Animals: [
    "elephant",
    "giraffe",
    "penguin",
    "dolphin",
    "kangaroo",
    "octopus",
    "butterfly",
    "cheetah",
    "koala",
    "peacock",
    "flamingo",
    "panda",
    "wolf",
    "eagle",
    "shark",
    "turtle",
    "fox",
    "owl",
    "zebra",
    "tiger",
  ],
  Food: [
    "pizza",
    "sushi",
    "burger",
    "pasta",
    "tacos",
    "curry",
    "sandwich",
    "salad",
    "soup",
    "steak",
    "cake",
    "cookie",
    "donut",
    "ice cream",
    "chocolate",
    "apple",
    "banana",
    "strawberry",
    "mango",
    "watermelon",
  ],
  Countries: [
    "japan",
    "brazil",
    "egypt",
    "canada",
    "australia",
    "france",
    "mexico",
    "india",
    "germany",
    "china",
    "italy",
    "spain",
    "russia",
    "korea",
    "thailand",
    "greece",
    "norway",
    "argentina",
    "morocco",
    "peru",
  ],
  Objects: [
    "laptop",
    "guitar",
    "umbrella",
    "camera",
    "bicycle",
    "clock",
    "mirror",
    "key",
    "pencil",
    "backpack",
    "headphones",
    "lamp",
    "wallet",
    "glasses",
    "chair",
    "table",
    "phone",
    "book",
    "cup",
    "pillow",
  ],
  Sports: [
    "soccer",
    "basketball",
    "tennis",
    "swimming",
    "volleyball",
    "baseball",
    "golf",
    "hockey",
    "boxing",
    "skiing",
    "surfing",
    "cycling",
    "yoga",
    "karate",
    "archery",
    "fencing",
    "cricket",
    "rugby",
    "gymnastics",
    "bowling",
  ],
  Professions: [
    "doctor",
    "teacher",
    "chef",
    "pilot",
    "artist",
    "engineer",
    "lawyer",
    "nurse",
    "architect",
    "scientist",
    "musician",
    "writer",
    "firefighter",
    "photographer",
    "dancer",
    "farmer",
    "mechanic",
    "designer",
    "actor",
    "programmer",
  ],
  Nature: [
    "mountain",
    "ocean",
    "forest",
    "desert",
    "river",
    "volcano",
    "waterfall",
    "island",
    "cave",
    "canyon",
    "beach",
    "lake",
    "meadow",
    "valley",
    "glacier",
    "jungle",
    "reef",
    "prairie",
    "cliff",
    "dune",
  ],
  Technology: [
    "smartphone",
    "computer",
    "internet",
    "robot",
    "satellite",
    "drone",
    "tablet",
    "bluetooth",
    "software",
    "algorithm",
    "database",
    "cloud",
    "server",
    "browser",
    "email",
    "wifi",
    "keyboard",
    "mouse",
    "monitor",
    "printer",
  ],
};

export const DEFAULT_CATEGORIES = Object.keys(WORD_CATEGORIES);

export const GAME_CONFIG = {
  TURN_DURATION: 60, // seconds
  MIN_ROTATIONS: 1,
  MAX_ROTATIONS: 5,
  MIN_SETS: 1,
  MAX_SETS: 10,
  POINTS_CORRECT_VOTE: 1000,
  POINTS_IMPOSTOR_WIN: 2000,
};

export const MESSAGES = {
  ROOM_FULL: "Room is full",
  GAME_IN_PROGRESS: "Game already in progress",
  ROOM_NOT_FOUND: "Room not found",
  NOT_HOST: "Only the host can perform this action",
  INVALID_VOTE: "Cannot vote for yourself",
  ALREADY_VOTED: "You have already voted",
};
